apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: product-management
data:
  NODE_ENV: "production"
  PORT: "5000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "productdb"
  CORS_ORIGIN: "http://localhost:3000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: product-management
data:
  POSTGRES_DB: "productdb"
