apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: product-management
type: Opaque
data:
  # Base64 encoded values
  # postgres:postgres
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
