---
# Main playbook for Product Management Application Deployment

- name: Setup Docker and Dependencies
  hosts: all
  become: yes
  roles:
    - docker
    - common

- name: Setup Kubernetes Cluster
  hosts: k8s_cluster
  become: yes
  roles:
    - kubernetes

- name: Deploy Application
  hosts: k8s_masters
  become: yes
  roles:
    - deploy-app

- name: Configure Monitoring
  hosts: k8s_cluster
  become: yes
  roles:
    - monitoring
